name = "MixedDistributions"
uuid = "93778f88-a5f2-11e8-358c-f9549ec425ce"
authors = ["matbesancon <mathieu.besancon@gmail.com>"]
version = "0.1.0"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
